version: '3'

services:

  manager:
    build: ./services/manager/
    command: python src/main.py
    restart: always
    volumes:
      - ./services/manager/src:/app/src
      - sender_log:/app/log
      - ./services/sender/date.db:/app/date.db
      - /var/run/docker.sock:/var/run/docker.sock
#      - ./docker/sender/screenshots:/app/screenshots
    env_file:
      - .env
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  mongo:
    image: mongo
    env_file:
      - .env
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}

  sender:
    build: ./services/sender/
    command: python src/main.py
#    restart: always
    volumes:
      - ./services/sender/src:/app/src
      - sender_log:/app/log
      - ./services/sender/date.db:/app/date.db
      - ./services/sender/screenshots:/app/screenshots
    env_file:
      - .env
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  browser:
    build: ./services/browser/
    command: /app/start-browser.sh
#    restart: always
    ports:
      - 9222:${CHROME_REMOTE_DEBUG_PORT}
    env_file:
      - .env
    volumes:
      - ./services/browser/start-browser.sh:/app/start-browser.sh

volumes:
  mongo_data: {}
  browser_data: {}
  sender_log: {}
